# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac4838bde8a202fda3918a10d408c4dae77e73d5c38933a03b2e7421d73210a70806b5cdf6b4cc6c834cc420ba02384db3b38250fa38d7a11e47dd401a1501fc

test:
  secret_key_base: afdd194056eea8262d44f638eff3f3d6676ae78d05e40315b3887d0a41d3ce428946fa8dcc0744436e83ee4cd5fcea7e80ab3da52f24d4c5681cc0540fad7229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
